version: '3'
services:
  llama:
    image: llama-cpp-container
    build:
      context: .
    ports:
      - "2231:22"
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

